### ISSUE TITLE
updated pip package

### ISSUE THREAD

**Issue by caphrim007** [barneygale/isoparser#8]
Hello,

Could you update the pip package to include the long_description fix that you committed? When I try to install it, I get the following

```
(ansible-2.0) SEA-ML-RUPP1:f5-ansible trupp$ pip install isoparser
Collecting isoparser
  Downloading isoparser-0.1.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/jc/9d1188j962931rhqrlm4173w5j5m45/T/pip-build-pe1410/isoparser/setup.py", line 11, in <module>
        long_description=open('README.rst').read(),
    IOError: [Errno 2] No such file or directory: 'README.rst'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/jc/9d1188j962931rhqrlm4173w5j5m45/T/pip-build-pe1410/isoparser/
```

**Comment by barneygale** [comment]
Could you give it a go now?

**Comment by caphrim007** [comment]
works like a charm! thanks @barneygale !
